### ISSUE TITLE
response from TAD

### ISSUE THREAD

**Issue by Kri-h** [rriley/qu-thesis#2]
Dear Dr.
Thank you for the template. Is it possible to change the font color. I have received a feedback from TAD. pls find,
•	Make sure the color of the text is black—appear as dark gray .
•	Figures/Tables should be centered ; although, figure/table captions should be aligned left.
•	 Double space (four lines) before the start of a table/figure .
Thank you very much Dr.
regards
Aparna

**Comment by rriley** [comment]
Hi Aparna,

Are you sure you are using the version from here (Github)?  Two of the things you mention are already part of the template.

1. The text is already black.
2. Figures/Tables are already centered.
3. The captions on figures/tables are already left aligned.
4.  There is not four lines before each figure.  I've just pushed a commit that does that.  It is 6a953e6807971927eafa46e3c7b5e6bccafbb9f3.  It consists of one line you can add to your Latex file in order to adjust the `\textfloatsep`

I hope this helps.

**Comment by Kri-h** [comment]
Dear Dr,
Thank you for quick response. May be I am using old version from github. I will try this.
Thank you very much,
Regards
Aparna

Sent from my iPhone

On Jan 23, 2018, at 12:53 PM, Ryan Riley <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Aparna,

Are you sure you are using the version from here (Github)? Two of things you mention are already part of the template.

  1.  The text is already black.
  2.  Figures/Tables are already centered.
  3.  The captions on figures/tables are already left aligned.
  4.  There is not four lines before each figure. I've just pushed a commit that does that. It is 6a953e6<https://github.com/rriley/qu-thesis/commit/6a953e6807971927eafa46e3c7b5e6bccafbb9f3>. It consists of one line you can add to your Latex file in order to adjust the \textfloatsep

I hope this helps.
